spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:horoscope_test;DB_CLOSE_DELAY=-1;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none